<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\CustomerController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/CustomerController.php';

return $this->services['App\Controller\CustomerController'] = new \App\Controller\CustomerController();
