<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDqwtuz5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDqwtuz5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDqwtuz5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDqwtuz5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDqwtuz5\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Dqwtuz5',
    'container.build_id' => '2d8e28ee',
    'container.build_time' => 1525166593,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDqwtuz5');
